Server:
  GRPC:
    Host: "0.0.0.0"
    Port: 9001
Service:
  Dao:
    Redis:
      Address: "127.0.0.1"
      Port: 6379
      Password: "tQF08UDhtu6g5VjghhYmag=="
      Database: 0
  OssClientConfig:
    AliYun:
      BucketName: "store-libong"
#    Local:
#      BucketService:
#        Host: "0.0.0.0"
#        Port: 9001

